/**
 * movies.js — CineClube
 *
 * Banco de dados dos filmes.
 * Cada objeto representa um filme com as seguintes propriedades:
 *
 *   title    {string}  — Título do filme
 *   year     {number}  — Ano de lançamento
 *   rating   {number}  — Nota (0–10)
 *   price    {string}  — Preço de aluguel formatado
 *   genre    {string}  — Gênero (usado pelo filtro): 'acao' | 'drama' | 'comedia' |
 *                        'terror' | 'ficcao' | 'animacao' | 'classico'
 *   badge    {string|null} — 'new' | 'hot' | 'classic' | null
 *   poster    {string}  — poster representando o poster (placeholder)
 *   bg       {string}  — Gradiente CSS do poster
 *   sinopse  {string}  — Descrição curta do filme
 */

const MOVIES = [
  {
    title:   'O Poderoso Chefão',
    year:    1972,
    rating:  9.2,
    price:   'R$7,90',
    genre:   'drama',
    badge:   'classic',
    poster:   './assets/posters/o-poderoso-chefao.png',
    bg:      'linear-gradient(135deg, #1a0a2e, #3d1a6e)',
    sinopse: 'A história épica da família Corleone, uma das mais poderosas organizações criminosas dos Estados Unidos. Um dos maiores filmes de todos os tempos.',
  },
  {
    title:   'Interestelar',
    year:    2014,
    rating:  8.6,
    price:   'R$9,90',
    genre:   'ficcao',
    badge:   'hot',
    poster:   './assets/posters/interstellar.png',
    bg:      'linear-gradient(135deg, #0d1b2a, #1b4f72)',
    sinopse: 'Um grupo de exploradores viaja por um buraco de minhoca no espaço na esperança de garantir a sobrevivência da humanidade. Épico científico de Christopher Nolan.',
  },
  {
    title:   'Coringa',
    year:    2019,
    rating:  8.4,
    price:   'R$8,90',
    genre:   'drama',
    badge:   'hot',
    poster:   './assets/posters/coringa.png',
    bg:      'linear-gradient(135deg, #1a1a1a, #4a4a4a)',
    sinopse: 'Arthur Fleck é um comediante fracassado de Gotham City que, após uma série de eventos traumáticos, se transforma no icônico vilão Coringa.',
  },
  {
    title:   'Matrix',
    year:    1999,
    rating:  8.7,
    price:   'R$6,90',
    genre:   'ficcao',
    badge:   'classic',
    poster:   './assets/posters/matrix.png',
    bg:      'linear-gradient(135deg, #0a1628, #1e3a5f)',
    sinopse: 'Neo descobre que a realidade que conhece é uma simulação computacional chamada Matrix, e se une a rebeldes para lutar contra as máquinas que escravizam a humanidade.',
  },
  {
    title:   'Mad Max: Estrada da Fúria',
    year:    2015,
    rating:  8.1,
    price:   'R$8,90',
    genre:   'acao',
    badge:   'hot',
    poster:   '🏎️',
    bg:      'linear-gradient(135deg, #1c0a00, #5c2500)',
    sinopse: 'Em um mundo pós-apocalíptico dominado pelo culto do combustível, Max une forças com Furiosa para escapar de um tirano e sua horda de cultistas.',
  },
  {
    title:   'Duna',
    year:    2021,
    rating:  7.9,
    price:   'R$10,90',
    genre:   'ficcao',
    badge:   'new',
    poster:   '🏜️',
    bg:      'linear-gradient(135deg, #000d1a, #003366)',
    sinopse: 'Paul Atreides, um jovem brilhante nascido com um destino grandioso, deve viajar para o planeta mais perigoso do universo para garantir o futuro de sua família e povo.',
  },
  {
    title:   'Tudo em Todo Lugar ao Mesmo Tempo',
    year:    2022,
    rating:  7.8,
    price:   'R$9,90',
    genre:   'ficcao',
    badge:   'new',
    poster:   '🌀',
    bg:      'linear-gradient(135deg, #1a0030, #600060)',
    sinopse: 'Uma imigrante chinesa é varrida em uma aventura de multiverso onde é a única capaz de salvar o mundo ao explorar as vidas que poderia ter levado.',
  },
  {
    title:   'Gravity',
    year:    2013,
    rating:  7.7,
    price:   'R$7,90',
    genre:   'ficcao',
    badge:   null,
    poster:   '🛸',
    bg:      'linear-gradient(135deg, #0f2027, #2c5364)',
    sinopse: 'Após um desastre, uma médica astronauta fica à deriva no espaço sem nenhuma forma de entrar em contato com a Terra enquanto os suprimentos de oxigênio diminuem.',
  },
  {
    title:   'Inception',
    year:    2010,
    rating:  8.8,
    price:   'R$8,90',
    genre:   'acao',
    badge:   'hot',
    poster:   '🌀',
    bg:      'linear-gradient(135deg, #16213e, #0f3460)',
    sinopse: 'Dom Cobb é um ladrão especialista na arte de extrair segredos do subconsciente durante o estado de sonho. Uma viagem épica pela mente humana.',
  },
  {
    title:   'O Iluminado',
    year:    1980,
    rating:  8.4,
    price:   'R$5,90',
    genre:   'terror',
    badge:   'classic',
    poster:   '🪓',
    bg:      'linear-gradient(135deg, #1a0000, #800000)',
    sinopse: 'Jack Torrance aceita um emprego de zelador de inverno em um hotel remoto e isolado, onde sua sanidade começa a deteriorar sob influências sobrenaturais.',
  },
  {
    title:   'Corra!',
    year:    2017,
    rating:  7.7,
    price:   'R$7,90',
    genre:   'terror',
    badge:   null,
    poster:   '👁️',
    bg:      'linear-gradient(135deg, #0d0d0d, #2d2d2d)',
    sinopse: 'Um jovem afro-americano visita os pais da namorada branca e descobre uma série de eventos perturbadores que revelam uma conspiração horrível.',
  },
  {
    title:   'Up — Altas Aventuras',
    year:    2009,
    rating:  8.2,
    price:   'R$6,90',
    genre:   'animacao',
    badge:   'classic',
    poster:   '🎈',
    bg:      'linear-gradient(135deg, #003080, #0070d0)',
    sinopse: 'Um idoso solitário une-se a um escoteiro curioso em uma extraordinária jornada voadora até as cataratas mais altas do mundo, em sua casa suspensa por balões.',
  },
  {
    title:   'Parasita',
    year:    2019,
    rating:  8.5,
    price:   'R$9,90',
    genre:   'drama',
    badge:   'hot',
    poster:   '🏠',
    bg:      'linear-gradient(135deg, #1a2a1a, #2d4a2d)',
    sinopse: 'A família Kim, toda desempregada, passa a fazer parte da vida da família Park, rica e ingênua. Uma obra-prima do cinema sul-coreano vencedora do Oscar.',
  },
  {
    title:   'A Forma da Água',
    year:    2017,
    rating:  7.3,
    price:   'R$7,90',
    genre:   'drama',
    badge:   null,
    poster:   '🌊',
    bg:      'linear-gradient(135deg, #00202a, #004a60)',
    sinopse: 'Durante a Guerra Fria, uma faxineira muda num laboratório secreto do governo forma um relacionamento único com uma criatura anfíbia capturada.',
  },
  {
    title:   'Superbad',
    year:    2007,
    rating:  7.6,
    price:   'R$5,90',
    genre:   'comedia',
    badge:   'classic',
    poster:   '😂',
    bg:      'linear-gradient(135deg, #1a0d00, #503000)',
    sinopse: 'Dois melhores amigos do ensino médio tentam aproveitar suas últimas semanas de escola, navegando por mal-entendidos e aventuras inesquecíveis.',
  },
  {
    title:   'Vizinhos',
    year:    2014,
    rating:  6.3,
    price:   'R$4,90',
    genre:   'comedia',
    badge:   null,
    poster:   '🏡',
    bg:      'linear-gradient(135deg, #2d1a00, #7a4700)',
    sinopse: 'Um casal de jovens pais descobre que uma fraternidade universitária barulhenta se mudou para a casa ao lado. Uma comédia irada e hilária.',
  },
];
